# Generated by Django 5.0.6 on 2024-07-08 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0003_alter_notebookcell_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.PositiveSmallIntegerField(choices=[(1, 'User'), (2, 'AI')])),
                ('content', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attached_image', models.ImageField(blank=True, null=True, upload_to='messages/images/')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='messages/files/')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebooks.notebook')),
            ],
        ),
    ]
