# Generated by Django 5.0.6 on 2024-07-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='author',
            new_name='author_type',
        ),
    ]
