# Generated by Django 5.0.6 on 2024-07-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_author_chatmessage_author_type'),
        ('notebooks', '0003_alter_notebookcell_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebooks.notebookcell'),
        ),
    ]
