# Generated by Django 5.0.6 on 2024-06-27 13:30

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBookDBConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.PositiveSmallIntegerField(choices=[(1, 'Postgres')])),
                ('db_name', models.CharField(max_length=100)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('db_host', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('db_port', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('db_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notebooks.notebookdbconfig')),
            ],
        ),
        migrations.CreateModel(
            name='NoteBookCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'SQL Code'), (2, 'Text')])),
                ('content', models.TextField(max_length=2000)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='notebooks.notebook')),
            ],
        ),
    ]
